text = input('Введите текст: ')
def stroka():
   print(text[2])
   print(text[-2])
   print(text[:5])
   print(text[:-2])
   print(text[::2])
   print(text[1::2])
   print(text[::-2])
   print(len(text))
stroka()